### ISSUE TITLE
When use run_demo.sh, it outputs'"GET / HTTP/1.1" 404 Not Found'

### ISSUE THREAD

**Issue by Labmem009** [LLaVA-VL/LLaVA-Interactive-Demo#2]
2023-11-03 10:40:36 | INFO | stdout | INFO:     127.0.0.1:14124 - "GET / HTTP/1.1" 404 Not Found

EnvironmentNameNotFound: Could not find conda environment: lama
You can list all discoverable environments with `conda info --envs`.

/LLaVA-Interactive-Demo/lama
Traceback (most recent call last):
  File "/LLaVA-Interactive-Demo/lama/../lama_server.py", line 7, in <module>
    import hydra
ModuleNotFoundError: No module named 'hydra'
2023-11-03 10:41:06 | INFO | stdout | INFO:     127.0.0.1:14122 - "GET / HTTP/1.1" 404 Not Found
Traceback (most recent call last):
  File "/LLaVA-Interactive-Demo/llava_interactive.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

And there is no conda env named 'lama', maybe I missed something in setup? But I just followed the README
I run run_demo.sh in 'llava_int' env created in setup.

**Comment by CREED404** [comment]
i had the same issue, i listed the Conda environments but i didn't find any of the two environments (lama and LLava), i found that the scripts uses `conda activate conda-env-name` so i changed all the line with this command to `source activate conda-env-name`, and it worked but i don't understand the **"GET / HTTP/1.1" 404 Not Found** error, BTW i am running it using WSL2 i also used the Dockerfile which i had to edit to build the container.
